# Generated by Django 5.0.6 on 2024-06-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tablaProductos',
            fields=[
                ('Código', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Producto', models.CharField(max_length=50)),
                ('Cantidad', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
